COMMENT =	command-line copy/paste utilities for Wayland

GH_ACCOUNT =	bugaevc
GH_PROJECT =	wl-clipboard
GH_TAGNAME =	v2.2.1

CATEGORIES =	wayland

# GPLv3+
PERMIT_PACKAGE = yes

COMPILIER =	base-clang ports-gcc
COMPILIER_LANGS = c

MODULES =	devel/meson

WANTLIB +=	wayland-client

LIB_DEPENDS =	wayland/wayland

.include <bsd.port.mk>
